package com.mycompany.graficadora;

import java.awt.Color;
import javax.swing.DefaultListModel;

public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Graphics
     */
    private Lienzo lienzo;
    private int idActual;
    DefaultListModel<Integer> modeloLista = new DefaultListModel<>();
    private int idUltimo;

    public Ventana() {
        initComponents();
        this.setLocationRelativeTo(null); // Para centrar el frame
        lienzo = new Lienzo(this.jPanel1);
        idActual = 0;
        idUltimo = 0;
        lista_Figuras.setModel(modeloLista);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        fondo = new javax.swing.JLabel();
        jButtonESCALAR = new javax.swing.JButton();
        btn_triangulo = new javax.swing.JButton();
        btn_circunferencia = new javax.swing.JButton();
        btn_ROTAR = new javax.swing.JButton();
        paintYellow = new javax.swing.JButton();
        bnt_dibSegmentado = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista_Figuras = new javax.swing.JList<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        moveUp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        moveDown = new javax.swing.JButton();
        moveRight = new javax.swing.JButton();
        moveLeft = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonESCALARMENOS = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        paintRed = new javax.swing.JButton();
        paintGreen = new javax.swing.JButton();
        paintBlue = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 0));
        setFocusTraversalPolicyProvider(true);
        setSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("CUADRADO");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 120, 20));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setEnabled(false);
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setVerifyInputWhenFocusTarget(false);

        fondo.setBackground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 1001, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButtonESCALAR.setText("+");
        jButtonESCALAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonESCALARMouseClicked(evt);
            }
        });
        jButtonESCALAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonESCALARActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonESCALAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 530, -1, -1));

        btn_triangulo.setText("TRIANGULO");
        btn_triangulo.setToolTipText("");
        btn_triangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_trianguloActionPerformed(evt);
            }
        });
        getContentPane().add(btn_triangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 120, 20));

        btn_circunferencia.setText("CIRCULO");
        btn_circunferencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_circunferenciaMouseClicked(evt);
            }
        });
        btn_circunferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_circunferenciaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_circunferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 120, 20));

        btn_ROTAR.setText("Rotar");
        btn_ROTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ROTARActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ROTAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 560, -1, -1));

        paintYellow.setBackground(new java.awt.Color(255, 255, 0));
        paintYellow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paintYellowMouseClicked(evt);
            }
        });
        paintYellow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paintYellowActionPerformed(evt);
            }
        });
        getContentPane().add(paintYellow, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 510, 20, 20));

        bnt_dibSegmentado.setText("DibujarSegmentado");
        bnt_dibSegmentado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_dibSegmentadoActionPerformed(evt);
            }
        });
        getContentPane().add(bnt_dibSegmentado, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 580, -1, -1));

        jLabel4.setText("Grosor");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 510, 60, -1));

        lista_Figuras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lista_FigurasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lista_Figuras);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 30, 150, 360));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DELGADO", "GRUESO" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 530, -1, -1));

        moveUp.setText("ʌ");
        moveUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moveUpMouseClicked(evt);
            }
        });
        moveUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveUpActionPerformed(evt);
            }
        });
        getContentPane().add(moveUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, 40, -1));

        jLabel1.setText("MOVER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, -1, -1));

        moveDown.setText("v");
        moveDown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moveDownMouseClicked(evt);
            }
        });
        moveDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveDownActionPerformed(evt);
            }
        });
        getContentPane().add(moveDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 560, 40, -1));

        moveRight.setText(">");
        moveRight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moveRightMouseClicked(evt);
            }
        });
        moveRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveRightActionPerformed(evt);
            }
        });
        getContentPane().add(moveRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 560, 40, -1));

        moveLeft.setText("<");
        moveLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moveLeftMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                moveLeftMouseEntered(evt);
            }
        });
        moveLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveLeftActionPerformed(evt);
            }
        });
        getContentPane().add(moveLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 560, 40, -1));

        jLabel2.setText("ESCALAR");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 510, -1, -1));

        jButtonESCALARMENOS.setText("-");
        jButtonESCALARMENOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonESCALARMENOSMouseClicked(evt);
            }
        });
        jButtonESCALARMENOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonESCALARMENOSActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonESCALARMENOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 530, -1, -1));

        jLabel3.setText("Pintar");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 490, -1, -1));

        paintRed.setBackground(new java.awt.Color(255, 51, 51));
        paintRed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paintRedMouseClicked(evt);
            }
        });
        paintRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paintRedActionPerformed(evt);
            }
        });
        getContentPane().add(paintRed, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 510, 20, 20));

        paintGreen.setBackground(new java.awt.Color(0, 204, 51));
        paintGreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paintGreenMouseClicked(evt);
            }
        });
        paintGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paintGreenActionPerformed(evt);
            }
        });
        getContentPane().add(paintGreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 540, 20, 20));

        paintBlue.setBackground(new java.awt.Color(51, 0, 255));
        paintBlue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paintBlueMouseClicked(evt);
            }
        });
        paintBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paintBlueActionPerformed(evt);
            }
        });
        getContentPane().add(paintBlue, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 510, 20, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Punto a = new Punto(2, 2);
        idUltimo++;
        Cuadrado c = new Cuadrado(a, idUltimo, 6);
        lienzo.aniadir(c);
        c.cambio = true;
        lienzo.ReDibujar();
        modeloLista.addElement(c.getID());
        lista_Figuras.setSelectedValue(c.getID(), true);
        idActual = idUltimo;
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    }//GEN-LAST:event_jButton1ActionPerformed
   
    private void jButtonESCALARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonESCALARMouseClicked
        
    }//GEN-LAST:event_jButtonESCALARMouseClicked

    private void btn_circunferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_circunferenciaActionPerformed
        idUltimo++;
        Circunferencia circ = new Circunferencia(idUltimo, 100, 100, 15);
        lienzo.aniadir(circ);
        circ.cambio = true;
        lienzo.ReDibujar();
        modeloLista.addElement(circ.getID());
        lista_Figuras.setSelectedValue(circ.getID(), true);
        idActual = idUltimo;
    }//GEN-LAST:event_btn_circunferenciaActionPerformed

    private void btn_circunferenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_circunferenciaMouseClicked
        
    }//GEN-LAST:event_btn_circunferenciaMouseClicked

    private void jButtonESCALARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonESCALARActionPerformed
        lienzo.getFigure(idActual).escalar(1.5);
        lienzo.getFigure(idActual).cambio = true;
        lienzo.ReDibujar();
    }//GEN-LAST:event_jButtonESCALARActionPerformed

    private void btn_trianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_trianguloActionPerformed
        idUltimo++;
        Triangulo tri = new Triangulo(idUltimo, 20);
        lienzo.aniadir(tri);
        tri.cambio = true;
        lienzo.ReDibujar();
        modeloLista.addElement(tri.getID());
        lista_Figuras.setSelectedValue(tri.getID(), true);
        idActual = idUltimo;
    }//GEN-LAST:event_btn_trianguloActionPerformed

    private void btn_ROTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ROTARActionPerformed
        lienzo.getFigure(idActual).rotar(45);
        lienzo.getFigure(idActual).cambio = true;
        lienzo.ReDibujar();
    }//GEN-LAST:event_btn_ROTARActionPerformed

    private void bnt_dibSegmentadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_dibSegmentadoActionPerformed
        boolean seg = lienzo.getFigure(idActual).segmentado;
        lienzo.getFigure(idActual).segmentado = !seg;
        lienzo.getFigure(idActual).cambio = true;
        lienzo.getFigure(idActual).cambio = true;
        lienzo.ReDibujar();
    }//GEN-LAST:event_bnt_dibSegmentadoActionPerformed

    private void paintYellowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paintYellowMouseClicked
        lienzo.getFigure(idActual).color = Color.YELLOW;
        lienzo.getFigure(idActual).cambio = true;
        lienzo.ReDibujar();
    }//GEN-LAST:event_paintYellowMouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        switch (jComboBox1.getSelectedIndex()){
            case 0: //Delgado
                lienzo.getFigure(idActual).grosor = false;
                break;
            case 1: //Grueso
                lienzo.getFigure(idActual).grosor = true;
                break;
        }
        lienzo.getFigure(idActual).cambio = true;
        lienzo.ReDibujar();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void lista_FigurasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lista_FigurasMouseClicked
        
        int indiceElemento = lista_Figuras.locationToIndex(evt.getPoint());
        idActual = modeloLista.getElementAt(indiceElemento);
    }//GEN-LAST:event_lista_FigurasMouseClicked

    private void moveUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveUpActionPerformed
     
    }//GEN-LAST:event_moveUpActionPerformed

    private void moveUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveUpMouseClicked
        lienzo.getFigure(idActual).traslacion(0,5);
        lienzo.getFigure(idActual).cambio = true;
        lienzo.ReDibujar();
    }//GEN-LAST:event_moveUpMouseClicked

    private void moveDownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveDownMouseClicked
        lienzo.getFigure(idActual).traslacion(0,-5);
        lienzo.getFigure(idActual).cambio = true;
        lienzo.ReDibujar();
    }//GEN-LAST:event_moveDownMouseClicked

    private void moveDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveDownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moveDownActionPerformed

    private void moveRightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveRightMouseClicked
        lienzo.getFigure(idActual).traslacion(5,0);
        lienzo.getFigure(idActual).cambio = true;
        lienzo.ReDibujar();
    }//GEN-LAST:event_moveRightMouseClicked

    private void moveRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveRightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moveRightActionPerformed

    private void moveLeftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveLeftMouseClicked
        lienzo.getFigure(idActual).traslacion(-5,0);
        lienzo.getFigure(idActual).cambio = true;
        lienzo.ReDibujar();
    }//GEN-LAST:event_moveLeftMouseClicked

    private void moveLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveLeftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moveLeftActionPerformed

    private void jButtonESCALARMENOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonESCALARMENOSMouseClicked
       lienzo.getFigure(idActual).escalar(0.5);
       lienzo.getFigure(idActual).cambio = true;
       lienzo.ReDibujar();
    }//GEN-LAST:event_jButtonESCALARMENOSMouseClicked

    private void jButtonESCALARMENOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonESCALARMENOSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonESCALARMENOSActionPerformed

    private void paintYellowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paintYellowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paintYellowActionPerformed

    private void paintRedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paintRedMouseClicked
        lienzo.getFigure(idActual).color = Color.RED;
        lienzo.getFigure(idActual).cambio = true;
        lienzo.ReDibujar();
    }//GEN-LAST:event_paintRedMouseClicked

    private void paintRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paintRedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paintRedActionPerformed

    private void paintGreenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paintGreenMouseClicked
        lienzo.getFigure(idActual).color = Color.GREEN;
        lienzo.getFigure(idActual).cambio = true;
        lienzo.ReDibujar();
    }//GEN-LAST:event_paintGreenMouseClicked

    private void paintGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paintGreenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paintGreenActionPerformed

    private void paintBlueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paintBlueMouseClicked
        lienzo.getFigure(idActual).color = Color.BLUE;
        lienzo.getFigure(idActual).cambio = true;
        lienzo.ReDibujar();
    }//GEN-LAST:event_paintBlueMouseClicked

    private void paintBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paintBlueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paintBlueActionPerformed

    private void moveLeftMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveLeftMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_moveLeftMouseEntered
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt_dibSegmentado;
    private javax.swing.JButton btn_ROTAR;
    private javax.swing.JButton btn_circunferencia;
    private javax.swing.JButton btn_triangulo;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonESCALAR;
    private javax.swing.JButton jButtonESCALARMENOS;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Integer> lista_Figuras;
    private javax.swing.JButton moveDown;
    private javax.swing.JButton moveLeft;
    private javax.swing.JButton moveRight;
    private javax.swing.JButton moveUp;
    private javax.swing.JButton paintBlue;
    private javax.swing.JButton paintGreen;
    private javax.swing.JButton paintRed;
    private javax.swing.JButton paintYellow;
    // End of variables declaration//GEN-END:variables
}
